version: '3.7'

services:

  node:
    container_name: nodeapp
    image: nodeapp
    build:
      context: .
      dockerfile: node.dockerfile
      args:
        PACKAGES: "nano wget curl"
    ports:
      - "3000:3000"
    networks:
      - nodeapp-network
    volumes:
      - ./logs:/var/www/logs
    environment:
      - NODE_ENV=production
      - APP_VERSION=1.0
    depends_on: 
      - mongodb # asegura que mongodb arranca primero, pero no asegura que estar치 disponible para aceptar conexiones
      
  mongodb:
    container_name: mongodb
    image: mongo # en este caso, como no tenemos build, lo que har치 es buscar una imagen llamada mongo en nuestro repositorio local, y si no la encuentra, ir치 a nuestro repositorio remoto por defecto (en este caso docker hub)
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge

# docker-compose build  Crea las im치genes para todos los servicios de nuestro docker-compose
# docker-compose up     El equivalente a docker run. Corre todos los componentes definidos en el docker-compose
# docker-compose down   Para todos los contenedores y los borra